# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9035cda4c0cc1d76115092596e01fdbc2dba279f866a3499250fef19a1ee65924298e22ea2928a907ec23003a6e972ff29d817da9a110b3ff24cf0f99665154e

test:
  secret_key_base: 4894fa6564a17eb800f5ea616fdae38df4d43b074739dc4ccf96a3b6b4fe8aa26197fe5ec9cbf02be085027e7ef5fd8f8186363e936e6023646c11548334e1e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
